### ISSUE TITLE
Executing "mv .env.example .env" is invalid.

### ISSUE THREAD

**Issue by Tuitefen** [ericet/auto-rarity#1]
![image](https://user-images.githubusercontent.com/81796525/134396896-62945e27-c80d-459c-8f50-6d4de5677bb4.png)
The final execution is like this, is this correct? He has been running.

**Comment by ericet** [comment]
You need to rename .env.example file to .env, then replace the YOUR_WALLET_PRIVATE_KEY with your private key.
The error just telling you that your private key is wrong.

**Comment by Tuitefen** [comment]
Thank you for your answer. I have replaced the private key, but failed to modify the file name. It told me that I must type the file name, and it is not allowed to start with. I'm confused,

**Comment by ericet** [comment]
I see you are using windows. You can simply go find the .env.example, and rename it.

**Comment by Tuitefen** [comment]
I understand that the command of Windows should be "rename .env.example .env". Thank you for your script and answer, thank you.
